### ISSUE TITLE
TaskBench dataset issue

### ISSUE THREAD

**Issue by yushengsu-thu** [belindal/TaskBench500#1]
When I unzip the datasets (TaskBenchData.tar.gz), it shows the the error message as follow: 
“x TaskBenchData/seq_composite/map/map{union(random{0}[eng](0),hyponyms[eng](0))}(S)/all.jsonl: truncated gzip input tar: Error exit delayed from previous errors.”

**Comment by belindal** [comment]
Hi! Thanks for pointing this out! You can use this link instead for now:
https://www.dropbox.com/s/wxe0c4gv1y1e3h8/TaskBenchData.tar.gz?dl=0
