### ISSUE TITLE
Upload dataset to stable repository

### ISSUE THREAD

**Issue by matthias-samwald** [belindal/TaskBench500#2]
The dataset should be uploaded to a stable, citable repository like https://zenodo.org/

Probably you have this on your todo list anyways, but this repo has been around for a while now. Thanks for the great paper and dataset! :)

**Comment by belindal** [comment]
Hi Matthias! Thanks for the feedback. There is a more persistent link uploaded on the Facebook servers at [dl.fbaipublicfiles.com/task_bench/taskbench500.tar.gz](url)
